/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareerCenterRouteImport } from './routes/career-center'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as LiveBatchesRouteImport } from './routes/live-batches'
import { Route as MobileAppsRouteImport } from './routes/mobile-apps'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'
import { Route as WorkRouteImport } from './routes/work'
import { Route as CoursePlayerSlugRouteImport } from './routes/course-player/$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify/$certificateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCenterRoute = CareerCenterRouteImport.update({
  id: '/career-center',
  path: '/career-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveBatchesRoute = LiveBatchesRouteImport.update({
  id: '/live-batches',
  path: '/live-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppsRoute = MobileAppsRouteImport.update({
  id: '/mobile-apps',
  path: '/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursePlayerSlugRoute = CoursePlayerSlugRouteImport.update({
  id: '/course-player/$slug',
  path: '/course-player/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/verify/$certificateId',
  path: '/verify/$certificateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/career-center': typeof CareerCenterRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/instructors': typeof InstructorsRoute
  '/internships': typeof InternshipsRoute
  '/learning-paths': typeof LearningPathsRoute
  '/live-batches': typeof LiveBatchesRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/payment-return': typeof PaymentReturnRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/web-development': typeof WebDevelopmentRoute
  '/work': typeof WorkRoute
  '/course-player/$slug': typeof CoursePlayerSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/career-center': typeof CareerCenterRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/instructors': typeof InstructorsRoute
  '/internships': typeof InternshipsRoute
  '/learning-paths': typeof LearningPathsRoute
  '/live-batches': typeof LiveBatchesRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/payment-return': typeof PaymentReturnRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/web-development': typeof WebDevelopmentRoute
  '/work': typeof WorkRoute
  '/course-player/$slug': typeof CoursePlayerSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/courses': typeof CoursesIndexRoute
  '/verify': typeof VerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/career-center': typeof CareerCenterRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/instructors': typeof InstructorsRoute
  '/internships': typeof InternshipsRoute
  '/learning-paths': typeof LearningPathsRoute
  '/live-batches': typeof LiveBatchesRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/payment-return': typeof PaymentReturnRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/web-development': typeof WebDevelopmentRoute
  '/work': typeof WorkRoute
  '/course-player/$slug': typeof CoursePlayerSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/career-center'
    | '/contact'
    | '/faq'
    | '/instructors'
    | '/internships'
    | '/learning-paths'
    | '/live-batches'
    | '/mobile-apps'
    | '/payment-return'
    | '/pricing'
    | '/projects'
    | '/resources'
    | '/services'
    | '/student-dashboard'
    | '/web-development'
    | '/work'
    | '/course-player/$slug'
    | '/courses/$slug'
    | '/verify/$certificateId'
    | '/courses/'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/career-center'
    | '/contact'
    | '/faq'
    | '/instructors'
    | '/internships'
    | '/learning-paths'
    | '/live-batches'
    | '/mobile-apps'
    | '/payment-return'
    | '/pricing'
    | '/projects'
    | '/resources'
    | '/services'
    | '/student-dashboard'
    | '/web-development'
    | '/work'
    | '/course-player/$slug'
    | '/courses/$slug'
    | '/verify/$certificateId'
    | '/courses'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/career-center'
    | '/contact'
    | '/faq'
    | '/instructors'
    | '/internships'
    | '/learning-paths'
    | '/live-batches'
    | '/mobile-apps'
    | '/payment-return'
    | '/pricing'
    | '/projects'
    | '/resources'
    | '/services'
    | '/student-dashboard'
    | '/web-development'
    | '/work'
    | '/course-player/$slug'
    | '/courses/$slug'
    | '/verify/$certificateId'
    | '/courses/'
    | '/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CareerCenterRoute: typeof CareerCenterRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InstructorsRoute: typeof InstructorsRoute
  InternshipsRoute: typeof InternshipsRoute
  LearningPathsRoute: typeof LearningPathsRoute
  LiveBatchesRoute: typeof LiveBatchesRoute
  MobileAppsRoute: typeof MobileAppsRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
  WorkRoute: typeof WorkRoute
  CoursePlayerSlugRoute: typeof CoursePlayerSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-center': {
      id: '/career-center'
      path: '/career-center'
      fullPath: '/career-center'
      preLoaderRoute: typeof CareerCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-batches': {
      id: '/live-batches'
      path: '/live-batches'
      fullPath: '/live-batches'
      preLoaderRoute: typeof LiveBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-apps': {
      id: '/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/mobile-apps'
      preLoaderRoute: typeof MobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-player/$slug': {
      id: '/course-player/$slug'
      path: '/course-player/$slug'
      fullPath: '/course-player/$slug'
      preLoaderRoute: typeof CoursePlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/verify/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CareerCenterRoute: CareerCenterRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InstructorsRoute: InstructorsRoute,
  InternshipsRoute: InternshipsRoute,
  LearningPathsRoute: LearningPathsRoute,
  LiveBatchesRoute: LiveBatchesRoute,
  MobileAppsRoute: MobileAppsRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
  WorkRoute: WorkRoute,
  CoursePlayerSlugRoute: CoursePlayerSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
