/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CareerCenterRouteImport } from './routes/career-center'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as LiveBatchesRouteImport } from './routes/live-batches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MobileAppsRouteImport } from './routes/mobile-apps'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBatchesRouteImport } from './routes/admin/batches'
import { Route as AdminCertificatesRouteImport } from './routes/admin/certificates'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as CoursePlayerSlugRouteImport } from './routes/course-player/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify/$certificateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCenterRoute = CareerCenterRouteImport.update({
  id: '/career-center',
  path: '/career-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveBatchesRoute = LiveBatchesRouteImport.update({
  id: '/live-batches',
  path: '/live-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppsRoute = MobileAppsRouteImport.update({
  id: '/mobile-apps',
  path: '/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/admin/batches',
  path: '/admin/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursePlayerSlugRoute = CoursePlayerSlugRouteImport.update({
  id: '/course-player/$slug',
  path: '/course-player/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/verify/$certificateId',
  path: '/verify/$certificateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/career-center': typeof CareerCenterRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/instructors': typeof InstructorsRoute
  '/internships': typeof InternshipsRoute
  '/learning-paths': typeof LearningPathsRoute
  '/live-batches': typeof LiveBatchesRoute
  '/login': typeof LoginRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/payment-return': typeof PaymentReturnRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/web-development': typeof WebDevelopmentRoute
  '/work': typeof WorkRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/course-player/$slug': typeof CoursePlayerSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/career-center': typeof CareerCenterRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/instructors': typeof InstructorsRoute
  '/internships': typeof InternshipsRoute
  '/learning-paths': typeof LearningPathsRoute
  '/live-batches': typeof LiveBatchesRoute
  '/login': typeof LoginRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/payment-return': typeof PaymentReturnRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/web-development': typeof WebDevelopmentRoute
  '/work': typeof WorkRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/course-player/$slug': typeof CoursePlayerSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/career-center': typeof CareerCenterRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/instructors': typeof InstructorsRoute
  '/internships': typeof InternshipsRoute
  '/learning-paths': typeof LearningPathsRoute
  '/live-batches': typeof LiveBatchesRoute
  '/login': typeof LoginRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/payment-return': typeof PaymentReturnRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/web-development': typeof WebDevelopmentRoute
  '/work': typeof WorkRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/course-player/$slug': typeof CoursePlayerSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/career-center'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/instructors'
    | '/internships'
    | '/learning-paths'
    | '/live-batches'
    | '/login'
    | '/mobile-apps'
    | '/payment-return'
    | '/pricing'
    | '/projects'
    | '/resources'
    | '/services'
    | '/signup'
    | '/student-dashboard'
    | '/web-development'
    | '/work'
    | '/admin/batches'
    | '/admin/certificates'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/orders'
    | '/course-player/$slug'
    | '/courses/$slug'
    | '/resources/$slug'
    | '/verify/$certificateId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/career-center'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/instructors'
    | '/internships'
    | '/learning-paths'
    | '/live-batches'
    | '/login'
    | '/mobile-apps'
    | '/payment-return'
    | '/pricing'
    | '/projects'
    | '/resources'
    | '/services'
    | '/signup'
    | '/student-dashboard'
    | '/web-development'
    | '/work'
    | '/admin/batches'
    | '/admin/certificates'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/orders'
    | '/course-player/$slug'
    | '/courses/$slug'
    | '/resources/$slug'
    | '/verify/$certificateId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/career-center'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/instructors'
    | '/internships'
    | '/learning-paths'
    | '/live-batches'
    | '/login'
    | '/mobile-apps'
    | '/payment-return'
    | '/pricing'
    | '/projects'
    | '/resources'
    | '/services'
    | '/signup'
    | '/student-dashboard'
    | '/web-development'
    | '/work'
    | '/admin/batches'
    | '/admin/certificates'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/orders'
    | '/course-player/$slug'
    | '/courses/$slug'
    | '/resources/$slug'
    | '/verify/$certificateId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CareerCenterRoute: typeof CareerCenterRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FaqRoute: typeof FaqRoute
  InstructorsRoute: typeof InstructorsRoute
  InternshipsRoute: typeof InternshipsRoute
  LearningPathsRoute: typeof LearningPathsRoute
  LiveBatchesRoute: typeof LiveBatchesRoute
  LoginRoute: typeof LoginRoute
  MobileAppsRoute: typeof MobileAppsRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
  WorkRoute: typeof WorkRoute
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  CoursePlayerSlugRoute: typeof CoursePlayerSlugRoute
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-center': {
      id: '/career-center'
      path: '/career-center'
      fullPath: '/career-center'
      preLoaderRoute: typeof CareerCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-batches': {
      id: '/live-batches'
      path: '/live-batches'
      fullPath: '/live-batches'
      preLoaderRoute: typeof LiveBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-apps': {
      id: '/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/mobile-apps'
      preLoaderRoute: typeof MobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/admin/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-player/$slug': {
      id: '/course-player/$slug'
      path: '/course-player/$slug'
      fullPath: '/course-player/$slug'
      preLoaderRoute: typeof CoursePlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/verify/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CareerCenterRoute: CareerCenterRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FaqRoute: FaqRoute,
  InstructorsRoute: InstructorsRoute,
  InternshipsRoute: InternshipsRoute,
  LearningPathsRoute: LearningPathsRoute,
  LiveBatchesRoute: LiveBatchesRoute,
  LoginRoute: LoginRoute,
  MobileAppsRoute: MobileAppsRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
  WorkRoute: WorkRoute,
  AdminBatchesRoute: AdminBatchesRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  CoursePlayerSlugRoute: CoursePlayerSlugRoute,
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
